package com.sun.corba.se.PortableActivationIDL;


/**
* com/sun/corba/se/PortableActivationIDL/InitialNameService.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from t:/workspace/src/java.corba/share/classes/com/sun/corba/se/PortableActivationIDL/activation.idl
* Monday, March 26, 2018 at 6:17:05 PM Pacific Daylight Time
*/


/** Interface used to support binding references in the bootstrap name
    * service.
    */
public interface InitialNameService extends InitialNameServiceOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface InitialNameService
